# OUTS 에는 있지만 INS 에는 없는 row
SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_OUTS O
LEFT JOIN ANIMAL_INS I ON O.ANIMAL_ID = I.ANIMAL_ID
# WHERE I.INTAKE_CONDITION IS NULL
WHERE I.ANIMAL_ID IS NULL
ORDER BY O.ANIMAL_ID ASC