name: Move Codetree Files

on:
  schedule:
    - cron: "0 9 * * *"  # 매일 한국 시간(KST) 18:00 (UTC 09:00)
  workflow_dispatch:  # 수동 실행 버튼 활성화

jobs:
  move-codetree-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if there were commits today
        id: check_commits
        run: |
          if git log --since="00:00" --until="23:59" --pretty=format:"%H" | grep -q .; then
            echo "TODAY_COMMIT=true" >> $GITHUB_ENV
          else
            echo "TODAY_COMMIT=false" >> $GITHUB_ENV
          fi

      - name: Move Codetree files
        if: env.TODAY_COMMIT == 'true'
        run: |
          mkdir -p Codetree
          MOVED=false
          for dir in [0-9][0-9][0-9][0-9][0-9][0-9]*; do
            if [ -d "$dir" ]; then
              mv "$dir" Codetree/
              MOVED=true
            fi
          done
          echo "MOVED=$MOVED" >> $GITHUB_ENV

      - name: Commit and push changes
        if: env.TODAY_COMMIT == 'true' && env.MOVED == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          name: Move Codetree Files

on:
  schedule:
    - cron: "0 9 * * *"  # 매일 한국 시간(KST) 18:00 (UTC 09:00)
  workflow_dispatch:  # 수동 실행 버튼 활성화

jobs:
  move-codetree-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if there were commits today
        id: check_commits
        run: |
          if git log --since="00:00" --until="23:59" --pretty=format:"%H" | grep -q .; then
            echo "TODAY_COMMIT=true" >> $GITHUB_ENV
          else
            echo "TODAY_COMMIT=false" >> $GITHUB_ENV
          fi

      - name: Move Codetree files
        if: env.TODAY_COMMIT == 'true'
        run: |
          mkdir -p Codetree
          MOVED=false
          for dir in [0-9][0-9][0-9][0-9][0-9][0-9]*; do
            if [ -d "$dir" ]; then
              mv "$dir" Codetree/
              MOVED=true
            fi
          done
          echo "MOVED=$MOVED" >> $GITHUB_ENV

      - name: Commit and push changes
        if: env.TODAY_COMMIT == 'true' && env.MOVED == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://$GH_TOKEN@github.com/$GITHUB_REPOSITORY.git  # PAT 사용
          git add .
          git commit -m "Move Codetree files to Codetree folder"
          git push

          git add .
          git commit -m "Move Codetree files to Codetree folder"
          git push

